In [1]:
import numpy as np

In [2]:
np_arr = np.arange(10_000_000)
np_arr = np_arr * 2

In [3]:
arr = list(range(10_000_000))
arr = [x * 2 for x in arr]

In [4]:
points = np.arange(-5, 5, 0.01)  # 1000 equally spaced points
points.shape

(1000,)

In [5]:
xs, ys = np.meshgrid(points, points)
xs.shape

(1000, 1000)

In [6]:
xs  # 列上保持一致，x轴

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [7]:
ys  # 行上保持一致，y轴

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [8]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

cond = np.array([True, False, True, True, False])

In [11]:
np.where(cond, xarr, yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [12]:
from random import normalvariate

N = 10_000_000


In [15]:
[normalvariate(0, 1) for _ in range(N)]

[-1.1089718967120124,
 -0.8669466563738302,
 -0.26824467321451806,
 1.2261315590022024,
 0.7087190843755706,
 1.0105705883414902,
 1.2242193246276574,
 -0.11791224461471639,
 -0.954298433922878,
 -1.6937271611852494,
 -1.8661575009486828,
 -1.230460869611066,
 1.034007114411791,
 -0.03784356469847413,
 -0.892491806277865,
 -0.3235445359545063,
 1.346001944679627,
 0.698308932760885,
 -0.30935954956454886,
 -1.678389407410925,
 0.7479270478853465,
 0.7523150321704835,
 -0.35158333387908586,
 0.37047780472606096,
 1.7860002306904097,
 0.6498982195361879,
 0.6218610988090513,
 0.03997732802560113,
 -0.2015385403870588,
 0.2516039012898002,
 -1.433560018151266,
 0.6223855088469981,
 -0.9927073983829728,
 0.06310584781862762,
 1.0443494311728003,
 2.6308734381648913,
 -0.18541559103459446,
 -0.1419714714244651,
 0.391161563345311,
 -1.0368921295043727,
 -1.625457262787604,
 -0.6938268169743774,
 0.7479643595317971,
 0.05627294105952145,
 -1.4722114089021832,
 -1.0809240079577644,
 -0.407784

In [16]:
np.random.standard_normal(N)

array([-0.5981508 ,  0.0793287 , -0.4089593 , ..., -1.56204715,
       -0.9424481 ,  0.9569271 ])

In [46]:
rng1 = np.random.RandomState(seed=42)
rng2 = np.random.default_rng(seed=42)

In [50]:
rng1.standard_normal((2, 3))

array([[ 0.24196227, -1.91328024, -1.72491783],
       [-0.56228753, -1.01283112,  0.31424733]])

In [54]:
rng2.standard_normal((2, 3))

array([[-0.42832782, -0.35213355,  0.53230919],
       [ 0.36544406,  0.41273261,  0.430821  ]])

In [64]:
arr = rng2.standard_normal((5, 4))
arr

array([[ 0.43442364,  0.2377356 , -0.59414996, -1.44605785],
       [ 0.07212951, -0.52949271,  0.23267621,  0.02185215],
       [ 1.60177889, -0.23935563, -1.02349749,  0.17927563],
       [ 0.21999668,  1.35918758,  0.83511125,  0.35687106],
       [ 1.46330289, -1.18876305, -0.63975153, -0.92657594]])

In [60]:
arr.sum(axis=0)  # 保留 axis = 0 轴

array([-1.92846112, -2.05259452, -2.21747002, -1.71049472])

In [61]:
arr.sum(axis=1)

array([ 0.0638831 , -5.45439335,  0.41536092, -0.75780364, -2.17606742])

In [65]:
(arr > 0)

array([[ True,  True, False, False],
       [ True, False,  True,  True],
       [ True, False, False,  True],
       [ True,  True,  True,  True],
       [ True, False, False, False]])

In [66]:
(arr > 0).sum()

12

In [68]:
arr.sort(axis=0)
arr

array([[ 0.07212951, -1.18876305, -1.02349749, -1.44605785],
       [ 0.21999668, -0.52949271, -0.63975153, -0.92657594],
       [ 0.43442364, -0.23935563, -0.59414996,  0.02185215],
       [ 1.46330289,  0.2377356 ,  0.23267621,  0.17927563],
       [ 1.60177889,  1.35918758,  0.83511125,  0.35687106]])

In [69]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * large_arr.size)]

-1.5255251709247388

1000